[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#008000"
magenta = "#b294bb"
red = "#9e1828"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.normal]
family = "Inconsolata-dz"

[font.offset]
x = -1
y = -3
