#!/bin/sh

if $(setxkbmap -query | grep -q "layout:\s*us"); then
    # If the current layout is 'us', switch to 'cz'
    setxkbmap cz -variant qwerty
    KBD="CZ"
else
    # Otherwise, switch to 'us'
    setxkbmap us
    KBD="US"
fi

# This will now work correctly
printf "%s" " $KBD"
