#!/bin/sh

# Taken from dwm_bar scripts
# Dependencies: xorg-setxkbmap

if setxkbmap -print | grep -q  "us"
then
  KBD="US" 
fi
if setxkbmap -print | grep -q "cz"
then
  KBD="CZ" 
fi

# echo " $KBD"
printf "%s" " $KBD"
