#!/bin/sh

# Taken from dwm-bar scripts

dwm_weather() {
        DATA=$(curl -s "wttr.in?format=1 | sed 's/ //' 🌨 +0°C")
        export __DWM_BAR_WEATHER__="${DATA}" 
}

dwm_weather
echo "${__DWM_BAR_WEATHER__}"
