#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)

if [ $status = Discharging ]; then
  if [ "$capacity" -gt 85 ]; then
    icon=""
  elif [ "$capacity" -le 85 -a "$capacity" -gt 60 ]; then
    icon=""
  elif [ "$capacity" -le 60 -a "$capacity" -gt 30 ]; then
    icon=""
  elif [ "$capacity" -le 30 -a "$capacity" -gt 10 ]; then
    icon=""
  elif [ "$capacity" -le 10 ]; then
    icon=""
  elif [ "$capacity" -le 5 ]; then
    icon="!"
  fi
else
  icon=""
fi
 
printf "%s" "$icon" "$capacity%"
